const languages=[['autodetect','Detect language'],['en','English'],['es','Spanish'],['fr','French'],['de','German'],['it','Italian'],['pt','Portuguese'],['pt-BR','Portuguese (Brazil)'],['nl','Dutch'],['ru','Russian'],['uk','Ukrainian'],['pl','Polish'],['tr','Turkish'],['ar','Arabic'],['hi','Hindi'],['bn','Bengali'],['ur','Urdu'],['zh-CN','Chinese (Simplified)'],['zh-TW','Chinese (Traditional)'],['ja','Japanese'],['ko','Korean'],['th','Thai'],['vi','Vietnamese'],['id','Indonesian'],['ms','Malay'],['sv','Swedish'],['da','Danish'],['no','Norwegian'],['fi','Finnish'],['el','Greek'],['he','Hebrew'],['cs','Czech'],['ro','Romanian'],['hu','Hungarian'],['fa','Persian'],['sw','Swahili']];
const source=document.querySelector('#source'),target=document.querySelector('#target'),input=document.querySelector('#input'),output=document.querySelector('#output'),button=document.querySelector('#translate'),buttonText=document.querySelector('#button-text'),count=document.querySelector('#count'),state=document.querySelector('#result-state'),copy=document.querySelector('#copy'),speak=document.querySelector('#speak'),clear=document.querySelector('#clear'),toast=document.querySelector('#toast');
function fillSelect(el,selected){el.innerHTML=languages.map(([code,name])=>`<option value="${code}">${name}</option>`).join('');el.value=selected}fillSelect(source,'en');fillSelect(target,'es');
let timer;function notify(message){toast.textContent=message;toast.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>toast.classList.remove('show'),2400)}
function setOutput(text,isError=false){output.textContent=text;output.classList.toggle('placeholder',!text||text==='Your translation will appear here.');output.classList.toggle('error',isError);copy.disabled=speak.disabled=isError||!text||text==='Your translation will appear here.'}
function setLoading(active){button.disabled=active;button.classList.toggle('loading',active);buttonText.textContent=active?'Translating…':'Translate'}
input.addEventListener('input',()=>{count.textContent=`${input.value.length} / 500`;clear.disabled=!input.value.trim();if(!input.value.trim()){setOutput('Your translation will appear here.');state.textContent='Ready when you are';state.classList.remove('error')}});
clear.addEventListener('click',()=>{input.value='';input.dispatchEvent(new Event('input'));input.focus()});
document.querySelector('#swap').addEventListener('click',()=>{if(source.value==='autodetect'){notify('Choose a source language before swapping.');return}const old=source.value;source.value=target.value;target.value=old;if(output.textContent!=='Your translation will appear here.'&&!output.classList.contains('error')){input.value=output.textContent;input.dispatchEvent(new Event('input'));setOutput('Your translation will appear here.');state.textContent='Ready when you are'}});
async function translate(){const text=input.value.trim();if(!text){input.focus();notify('Type a phrase to get started.');return}if(source.value===target.value){notify('Choose two different languages.');return}setLoading(true);state.textContent='Connecting to translation service…';state.classList.remove('error');setOutput('');try{const params=new URLSearchParams({q:text,langpair:`${source.value}|${target.value}`});const response=await fetch(`https://api.mymemory.translated.net/get?${params.toString()}`,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error(response.status===429?'The translation service is busy. Please try again shortly.':'The translation service could not complete your request.');const data=await response.json();if(data.responseStatus!==200)throw new Error(data.responseDetails||'No translation was returned. Please try another phrase.');const result=data.responseData?.translatedText;if(!result)throw new Error('No translation was returned. Please try again.');setOutput(result);state.textContent='Translation complete';}catch(error){setOutput(error.message||'Something went wrong. Please check your connection and try again.',true);state.textContent='Translation unavailable';state.classList.add('error')}finally{setLoading(false)}}
button.addEventListener('click',translate);input.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')translate()});copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(output.textContent);notify('Translation copied.')}catch{const range=document.createRange();range.selectNodeContents(output);getSelection().removeAllRanges();getSelection().addRange(range);notify('Select and copy the highlighted translation.')}});speak.addEventListener('click',()=>{if(!('speechSynthesis'in window)){notify('Text-to-speech is not available in this browser.');return}speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(output.textContent);utterance.lang=target.value==='zh-CN'?'zh-CN':target.value==='pt-BR'?'pt-BR':target.value; speechSynthesis.speak(utterance)});
